stage('Build') {
    steps {
        echo 'Compiling Smart Student Manager...'
        bat 'cd Task-7 && mvn clean compile -B'
    }
}

stage('Unit Tests') {
    steps {
        echo 'Running JUnit tests...'
        bat 'cd Task-7 && mvn test -B'
    }
    post {
        always {
            junit 'Task-7/target/surefire-reports/*.xml'
        }
    }
}

stage('Code Quality - SonarQube') {
    steps {
        echo 'Running SonarQube analysis...'
        bat "cd Task-7 && mvn sonar:sonar -Dsonar.projectKey=%APP_NAME% -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.login=%SONAR_TOKEN% -B"
    }
    post {
        success {
            echo 'SonarQube analysis complete! View at http://localhost:9000'
        }
    }
}

stage('Package') {
    steps {
        echo 'Packaging into JAR...'
        bat 'cd Task-7 && mvn package -DskipTests -B'
    }
    post {
        success {
            archiveArtifacts artifacts: 'Task-7/target/*.jar',
                             fingerprint: true
        }
    }
}